### ISSUE TITLE
Please add/export versions of the model that use Huggingface Safetensors

### ISSUE THREAD

**Issue by todd-cook** [ai-forever/sage#18]
To use your model and promote your work, it would help if the Huggingface models provided files that use Safetensors (Huggingface's format) which is preferred for security and reproducibility.

e.g.: 
* https://huggingface.co/ai-forever/T5-large-spell/tree/main
* https://huggingface.co/docs/safetensors/en/index

**Comment by meduzick** [comment]
Hi, @todd-cook!

Thanks for bringing that up, we have uploaded Safetensors variants of our models in both [first](https://huggingface.co/collections/ai-forever/sage-v100-release-66acd71334bfa59f7c341e0b) and [latest](https://huggingface.co/collections/ai-forever/sage-v110-release-660abac12d0769b9c67be501) releases of SAGE. Feel free to use them and ask any questions, if you have any 🌿
